#!/bin/sh
cd "${0%build}" || exit 1

build() {
	${X}gcc -c -O2 $C src/strbuf.c src/lua_cjson.c src/fpconv.c -I../lua-headers \
		-Wall -pedantic -DDISABLE_INVALID_NUMBERS
	${X}gcc *.o -shared -o ../../bin/$P/clib/$D $L
	rm -f      ../../bin/$P/$A
	${X}ar rcs ../../bin/$P/$A *.o
	rm *.o
}

if [ "$OSTYPE" = "msys" ]; then
	P=windows D=cjson.dll A=cjson.a \
	L="-s -static-libgcc -L../../bin/windows -llua51" build
elif [ "${OSTYPE#darwin}" != "$OSTYPE" ]; then
	P=osx D=cjson.so A=libcjson.a C="-arch x86_64" \
	L="-arch x86_64 -undefined dynamic_lookup -Wno-static-in-inline" build
else
	P=linux C=-fPIC L="-s -static-libgcc" D=cjson.so A=libcjson.a build
fi
