#!/bin/sh
cd "${0%build}" || exit 1

build() {
	${X}gcc -c -O2 $C md5.c -Wall -I.
	${X}gcc *.o -shared -o ../../bin/$P/$D $L
	rm -f      ../../bin/$P/$A
	${X}ar rcs ../../bin/$P/$A *.o
	rm *.o
}

if [ "$OSTYPE" = "msys" ]; then
	P=windows L="-s -static-libgcc" D=md5.dll A=md5.a build
elif [ "${OSTYPE#darwin}" != "$OSTYPE" ]; then
	P=osx C="-arch x86_64" L="-arch x86_64 -install_name @rpath/libmd5.dylib" \
	D=libmd5.dylib A=libmd5.a build
else
	P=linux C="-fPIC" L="-s -static-libgcc" D=libmd5.so A=libmd5.a build
fi
