#!/bin/sh
#go@ sh build
#go@ plink d10 sdk/c/pillow_simd/build
cd "${0%build}" || exit 1

build() {
	${X}gcc -O3 -c -Isrc/src/libImaging -I. $C \
		-DHAVE_PROTOTYPES \
		-DSTDC_HEADERS \
		-DSIZEOF_SHORT=2 \
		-DSIZEOF_INT=4 \
		-DSIZEOF_LONG_LONG=8 \
		src/src/libImaging/Resample.c \
		src/src/libImaging/Storage.c \
		src/src/libImaging/Copy.c \
		src/src/libImaging/Palette.c \
		Python.c \
		pillow_simd.c
	${X}gcc -Wl,--version-script=pillow_simd.version *.o -shared -o ../../bin/$P/$D $L
	rm -f      ../../bin/$P/$A
	${X}ar rcs ../../bin/$P/$A *.o
	rm *.o
}

build_s() {
	if [ "$OSTYPE" = "msys" ]; then
		P=windows L="-s -static-libgcc" D=pillow_simd$S.dll A=pillow_simd$S.a build
	elif [ "${OSTYPE#darwin}" != "$OSTYPE" ]; then
		P=osx64 C="$C -arch x86_64 -DSIZEOF_LONG=8" \
		L="-arch x86_64 -install_name @rpath/libboxblur.dylib" \
		D=libpillow_simd$S.dylib A=libpillow_simd$S.a build
	else
		P=linux C="$C -fPIC" L="-s -static-libgcc -DSIZEOF_LONG=8" \
		D=libpillow_simd$S.so A=libpillow_simd$S.a build
	fi
}
C="-msse4.2"       build_s
C="-mavx2" S=_avx2 build_s
