#!/bin/sh
cd "${0%build}" || exit 1

build() {
	${X}gcc -c -O2 $C sha2.c -I. -DSHA2_USE_INTTYPES_H -DBYTE_ORDER -DLITTLE_ENDIAN
	${X}gcc *.o -shared -o ../../bin/$P/$D $L
	rm -f      ../../bin/$P/$A
	${X}ar rcs ../../bin/$P/$A *.o
	rm *.o
}

if [ "$OSTYPE" = "msys" ]; then
	P=windows L="-s -static-libgcc" D=sha2.dll A=sha2.a build
elif [ "${OSTYPE#darwin}" != "$OSTYPE" ]; then
	P=osx C="-arch x86_64" L="-arch x86_64 -install_name @rpath/libsha2.dylib" \
	D=libsha2.dylib A=libsha2.a build
else
	P=linux C="-fPIC" L="-s -static-libgcc" D=libsha2.so A=libsha2.a build
fi
