--[==[

	webb | language/country/currency support
	Written by Cosmin Apreutesei. Public Domain.

]==]

require'webb_query'
require'schema'

function webb.lang_schema()

	tables.lang = {
		lang                , lang, pk,
		rtl                 , bool0,
		en_name             , name, not_null, uk(en_name),
		name                , name, not_null, uk(name),
		decimal_separator   , str, {maxlen = 4, size = 16}, utf8_bin, not_null, default ',',
		thousands_separator , str, {maxlen = 4, size = 16}, utf8_bin, not_null, default '.',
		supported           , bool0,
	}

	--https://en.wikipedia.org/wiki/Languages_used_on_the_Internet
	--https://meta.wikimedia.org/wiki/Template:List_of_language_names_ordered_by_code
	tables.lang.rows = {
		{'en', false, 'English'    , 'English',          '.', ',', true},
		{'ru', false, 'Russian'    , 'Русский',          ',', '.', false},
		{'tr', false, 'Turkish'    , 'Türkçe',           ',', '.', false},
		{'es', false, 'Spanish'    , 'Español',          ',', '.', false},
		{'fa', true , 'Persian'    , 'فارسی',              '٫' , '٬', false},
		{'fr', false, 'French'     , 'Français',         ',', '.', false},
		{'de', false, 'German'     , 'Deutsch',          ',', '.', false},
		{'ja', false, 'Japanese'   , '日本語',             '.', ',', false},
		{'vi', false, 'Vietnamese' , 'Việtnam',          ',', '.', false},
		{'zh', false, 'Chinese'    , '中文',              '.', ',', false},
		{'ar', true , 'Arabic'     , 'العربية',              '٫‎' , '٬', false},
		{'pt', false, 'Portuguese' , 'Português',        ',', '.', false},
		{'el', false, 'Greek'      , 'Ελληνικά',         ',', '.', false},
		{'it', false, 'Italian'    , 'Italiano',         ',', '.', false},
		{'id', false, 'Indonesian' , 'Bahasa Indonesia', ',', '.', false},
		{'uk', false, 'Ukrainian'  , 'Українська',       ',', '.', false},
		{'pl', false, 'Polish'     , 'Polski',           ',', '.', false},
		{'nl', false, 'Dutch'      , 'Nederlands',       ',', '.', false},
		{'ko', false, 'Korean'     , '한국어',            '.', ',', false},
		{'he', true , 'Hebrew'     , 'עברית',            '.', ',', false},
		{'th', false, 'Thai'       , 'ไทย',                '.', ',', false},
		{'cs', false, 'Czech'      , 'Česky',            ',', '.', false},
		{'ro', false, 'Romanian'   , 'Română',           ',', '.', false},
		{'sv', false, 'Swedish'    , 'Svenska',          ',', '.', false},
		{'sr', false, 'Serbian'    , 'Српски',           ',', '.', false},
		{'hu', false, 'Hungarian'  , 'Magyar',           ',', '.', false},
		{'da', false, 'Danish'     , 'Dansk',            ',', '.', false},
		{'bg', false, 'Bulgarian'  , 'Български',        ',', '.', false},
		{'fi', false, 'Finnish'    , 'Suomi',            ',', '.', false},
		{'sk', false, 'Slovak'     , 'Slovenčina',       ',', '.', false},
		{'hr', false, 'Croatian'   , 'Hrvatski',         ',', '.', false},
		{'hi', false, 'Hindi'      , 'हिन्दी',               '.', ',', false},
		{'lt', false, 'Lithuanian' , 'Lietuvių',         ',', '.', false},
		{'no', false, 'Norwegian'  , 'Norsk',            ',', '.', false},
		{'sl', false, 'Slovenian'  , 'Slovenščina',      ',', '.', false},
		{'ms', false, 'Malay'      , 'Bahasa Melayu',    '.', ',', false},
		{'ca', false, 'Catalan'    , 'Català',           '.', ',', false},
		{'sq', false, 'Albanian'   , 'Shqip',            '.', ',', false},
		--less spoken but official languages
		--TODO: separators, see https://en.wikipedia.org/wiki/Decimal_separator
		{'am', false, 'Amharic'    , 'አማርኛ',            '.', ',', false},
		{'as', false, 'Assamese'   , 'অসমীয়া',           '.', ',', false},
		{'az', false, 'Azerbaijani', 'آذربايجان',           '.', ',', false},
		{'be', false, 'Belarusian' , 'Беларуская',       '.', ',', false},
		{'bi', false, 'Bislama'    , 'Bislama',          '.', ',', false},
		{'bn', false, 'Bengali'    , 'বাংলা',             '.', ',', false},
		{'bs', false, 'Bosnian'    , 'Bosanski',         '.', ',', false},
		{'dv', true , 'Divehi'     , 'ދިވެހިބަސް',           '.', ',', false},
		{'dz', false, 'Dzongkha'   , 'ཇོང་ཁ',                '.', ',', false},
		{'et', false, 'Estonian'   , 'Eesti',            '.', ',', false},
		{'fo', false, 'Faroese'    , 'Føroyskt',         '.', ',', false},
		{'hy', false, 'Armenian'   , 'Հայերեն',          '.', ',', false},
		{'is', false, 'Icelandic'  , 'Íslenska',         '.', ',', false},
		{'ka', false, 'Georgian'   , 'ქართული',        '.', ',', false},
		{'kk', false, 'Kazakh'     , 'Қазақша',          '.', ',', false},
		{'kl', false, 'Greenlandic', 'Kalaallisut',      '.', ',', false},
		{'km', false, 'Cambodian'  , 'ភាសាខ្មែរ',           '.', ',', false},
		{'ky', false, 'Kirghiz'    , 'Кыргызча',         '.', ',', false},
		{'lb', false, 'Luxembourgish', 'Lëtzebuergesch', '.', ',', false},
		{'lo', false, 'Laotian'    , 'ລາວ',              '.', ',', false},
		{'lv', false, 'Latvian'    , 'Latviešu',         '.', ',', false},
		{'mg', false, 'Malagasy'   , 'Malagasy',         '.', ',', false},
		{'mi', false, 'Māori'      , 'Māori',            '.', ',', false},
		{'mk', false, 'Macedonian' , 'Македонски',       '.', ',', false},
		{'mn', false, 'Mongolian'  , 'Монгол',           '.', ',', false},
		{'mt', false, 'Maltese'    , 'Malti',            '.', ',', false},
		{'my', false, 'Burmese'    , 'Myanmasa',         '.', ',', false},
		{'na', false, 'Nauruan'    , 'Dorerin Naoero',   '.', ',', false},
		{'ne', false, 'Nepali'     , 'नेपाली',              '.', ',', false},
		{'rw', false, 'Rwandi'     , 'Kinyarwandi',      '.', ',', false},
		{'si', false, 'Sinhalese'  , 'සිංහල',            '.', ',', false},
		{'sm', false, 'Samoan'     , 'Gagana Samoa',     '.', ',', false},
		{'so', false, 'Somalia'    , 'Soomaaliga',       '.', ',', false},
		{'sw', false, 'Swahili'    , 'Kiswahili',        '.', ',', false},
		{'tg', false, 'Tajik'      , 'Тоҷикӣ',           '.', ',', false},
		{'ti', false, 'Tigrinya'   , 'ትግርኛ',            '.', ',', false},
		{'tk', false, 'Turkmen'    , 'تركمن',             '.', ',', false},
		{'uz', false, 'Uzbek'      , 'Ўзбек',            '.', ',', false},
	}

	tables.currency = {
		currency    , currency, not_null, pk,
		decimals    , int16, not_null,
		en_name     , name, not_null, uk(currency, en_name),
		symbol      , name,
	}

	--https://en.wikipedia.org/wiki/List_of_circulating_currencies
	tables.currency.rows = {
		{'AED', 2, 'United Arab Emirates dirham'             , 'د.إ'},
		{'AFN', 2, 'Afghan afghani'                          , '؋'},
		{'ALL', 2, 'Albanian lek'                            , 'L'},
		{'AMD', 2, 'Armenian dram'                           , '֏'},
		{'ANG', 2, 'Netherlands Antillean guilder'           , 'ƒ'},
		{'AOA', 2, 'Angolan kwanza'                          , 'Kz'},
		{'ARS', 2, 'Argentine peso'                          , '$'},
		{'AUD', 2, 'Australian dollar'                       , '$'},
		{'AWG', 2, 'Aruban florin'                           , 'ƒ'},
		{'AZN', 2, 'Azerbaijani manat'                       , '₼'},
		{'BAM', 2, 'Bosnia and Herzegovina convertible mark' , 'KM'},
		{'BBD', 2, 'Barbadian dollar'                        , '$'},
		{'BDT', 2, 'Bangladeshi taka'                        , '৳'},
		{'BGN', 2, 'Bulgarian lev'                           , 'лв'},
		{'BHD', 3, 'Bahraini dinar'                          , '.د.ب'},
		{'BIF', 0, 'Burundian franc'                         , 'Fr'},
		{'BMD', 2, 'Bermudian dollar'                        , '$'},
		{'BND', 2, 'Brunei dollar'                           , '$'},
		{'BOB', 2, 'Bolivian boliviano'                      , 'Bs'},
		{'BRL', 2, 'Brazilian real'                          , 'R$'},
		{'BSD', 2, 'Bahamian dollar'                         , '$'},
		{'BTN', 2, 'Bhutanese ngultrum'                      , 'Nu'},
		{'BWP', 2, 'Botswana pula'                           , 'P'},
		{'BYN', 0, 'Belarusian ruble'                        , 'Br'},
		{'BZD', 2, 'Belize dollar'                           , '$'},
		{'CAD', 2, 'Canadian dollar'                         , '$'},
		{'CDF', 2, 'Congolese franc'                         , 'Fr'},
		{'CHF', 2, 'Swiss franc'                             , 'Fr'},
		{'CKD', 2, 'Cook Islands dollar'                     , '$'},
		{'CLP', 0, 'Chilean peso'                            , '$'},
		{'CNY', 2, 'Chinese yuan'                            , '¥'},
		{'COP', 2, 'Colombian peso'                          , '$'},
		{'CRC', 2, 'Costa Rican colón'                       , '₡'},
		{'CUP', 2, 'Cuban peso'                              , '$'},
		{'CVE', 0, 'Cape Verdean escudo'                     , '$'},
		{'CZK', 2, 'Czech koruna'                            , 'Kč'},
		{'DJF', 0, 'Djiboutian franc'                        , 'Fr'},
		{'DKK', 2, 'Danish krone'                            , 'kr'},
		{'DOP', 2, 'Dominican peso'                          , 'RD$'},
		{'DZD', 2, 'Algerian dinar'                          , 'د.ج'},
		{'EGP', 2, 'Egyptian pound'                          , 'ج.م'},
		{'ERN', 2, 'Eritrean nakfa'                          , 'Nfk'},
		{'ETB', 2, 'Ethiopian birr'                          , 'Br'},
		{'EUR', 2, 'Euro'                                    , '€'},
		{'FJD', 2, 'Fijian dollar'                           , '$'},
		{'FKP', 2, 'Falkland Islands pound'                  , '£'},
		{'FOK', 2, 'Faroese króna'                           , 'kr'},
		{'GBP', 2, 'British pound'                           , '£'},
		{'GEL', 2, 'Georgian lari'                           , '₾'},
		{'GGP', 2, 'Guernsey pound'                          , '£'},
		{'GHS', 2, 'Ghanaian cedi'                           , '₵'},
		{'GIP', 2, 'Gibraltar pound'                         , '£'},
		{'GMD', 2, 'Gambian dalasi'                          , 'D'},
		{'GNF', 0, 'Guinean franc'                           , 'Fr'},
		{'GTQ', 2, 'Guatemalan quetzal'                      , 'Q'},
		{'GYD', 2, 'Guyanese dollar'                         , '$'},
		{'HKD', 2, 'Hong Kong dollar'                        , '$'},
		{'HNL', 2, 'Honduran lempira'                        , 'L'},
		{'HRK', 2, 'Croatian kuna'                           , 'kn'},
		{'HTG', 2, 'Haitian gourde'                          , 'G'},
		{'HUF', 2, 'Hungarian forint'                        , 'Ft'},
		{'IDR', 2, 'Indonesian rupiah'                       , 'Rp'},
		{'ILS', 2, 'Israeli new shekel'                      , '₪'},
		{'IMP', 2, 'Manx pound'                              , '£'},
		{'INR', 2, 'Indian rupee'                            , '₹'},
		{'IQD', 3, 'Iraqi dinar'                             , 'ع.د'},
		{'IRR', 0, 'Iranian rial'                            , '﷼'},
		{'ISK', 0, 'Icelandic króna'                         , 'kr'},
		{'JEP', 2, 'Jersey pound'                            , '£'},
		{'JMD', 2, 'Jamaican dollar'                         , '$'},
		{'JOD', 3, 'Jordanian dinar'                         , 'د.ا'},
		{'JPY', 0, 'Japanese yen'                            , '¥'},
		{'KES', 2, 'Kenyan shilling'                         , 'Sh'},
		{'KGS', 2, 'Kyrgyzstani som'                         , 'с'},
		{'KHR', 2, 'Cambodian riel'                          , '៛'},
		{'KID', 2, 'Kiribati dollar'                         , '$'},
		{'KMF', 0, 'Comorian franc'                          , 'Fr'},
		{'KPW', 0, 'North Korean won'                        , '₩'},
		{'KRW', 0, 'South Korean won'                        , '₩'},
		{'KWD', 3, 'Kuwaiti dinar'                           , 'د.ك'},
		{'KYD', 2, 'Cayman Islands dollar'                   , '$'},
		{'KZT', 2, 'Kazakhstani tenge'                       , '₸'},
		{'LAK', 0, 'Lao kip'                                 , '₭'},
		{'LBP', 0, 'Lebanese pound'                          , 'ل.ل'},
		{'LKR', 2, 'Sri Lankan rupee'                        , 'Rs'},
		{'LRD', 2, 'Liberian dollar'                         , '$'},
		{'LSL', 2, 'Lesotho loti'                            , 'L'},
		{'LYD', 3, 'Libyan dinar'                            , 'ل.د'},
		{'MAD', 2, 'Moroccan dirham'                         , 'د.م'},
		{'MDL', 2, 'Moldovan leu'                            , 'L'},
		{'MGA', 0, 'Malagasy ariary'                         , 'Ar'},
		{'MKD', 0, 'Macedonian denar'                        , 'ден'},
		{'MMK', 0, 'Burmese kyat'                            , 'Ks'},
		{'MNT', 2, 'Mongolian tögrög'                        , '₮'},
		{'MOP', 2, 'Macanese pataca'                         , 'MOP$'},
		{'MRU', 0, 'Mauritanian ouguiya'                     , 'UM'},
		{'MUR', 2, 'Mauritian rupee'                         , '₨'},
		{'MVR', 2, 'Maldivian rufiyaa'                       , '.ރ'},
		{'MWK', 2, 'Malawian kwacha'                         , 'MK'},
		{'MXN', 2, 'Mexican peso'                            , '$'},
		{'MYR', 2, 'Malaysian ringgit'                       , 'RM'},
		{'MZN', 2, 'Mozambican metical'                      , 'MT'},
		{'NAD', 2, 'Namibian dollar'                         , '$'},
		{'NGN', 2, 'Nigerian naira'                          , '₦'},
		{'NIO', 2, 'Nicaraguan córdoba'                      , 'C$'},
		{'NOK', 2, 'Norwegian krone'                         , 'kr'},
		{'NPR', 2, 'Nepalese rupee'                          , 'रू'},
		{'NZD', 2, 'New Zealand dollar'                      , '$'},
		{'OMR', 3, 'Omani rial'                              , 'ر.ع'},
		{'PAB', 2, 'Panamanian balboa'                       , 'B/.'},
		{'PEN', 2, 'Peruvian sol'                            , 'S/.'},
		{'PGK', 2, 'Papua New Guinean kina'                  , 'K'},
		{'PHP', 2, 'Philippine peso'                         , '₱'},
		{'PKR', 2, 'Pakistani rupee'                         , '₨'},
		{'PLN', 2, 'Polish złoty'                            , 'zł'},
		{'PND', 2, 'Pitcairn Islands dollar'                 , '$'},
		{'PRB', 2, 'Transnistrian ruble'                     , 'р'},
		{'PYG', 0, 'Paraguayan guaraní'                      , '₲'},
		{'QAR', 2, 'Qatari riyal'                            , 'ر.ق'},
		{'RON', 2, 'Romanian leu'                            , 'lei'},
		{'RSD', 2, 'Serbian dinar'                           , 'дин'},
		{'RUB', 2, 'Russian ruble'                           , '₽'},
		{'RWF', 0, 'Rwandan franc'                           , 'Fr'},
		{'SAR', 2, 'Saudi riyal'                             , '﷼'},
		{'SBD', 2, 'Solomon Islands dollar'                  , '$'},
		{'SCR', 2, 'Seychellois rupee'                       , '₨'},
		{'SDG', 2, 'Sudanese pound'                          , 'ج.س'},
		{'SEK', 2, 'Swedish krona'                           , 'kr'},
		{'SGD', 2, 'Singapore dollar'                        , '$'},
		{'SHP', 2, 'Saint Helena pound'                      , '£'},
		{'SLL', 0, 'Sierra Leonean leone'                    , 'Le'},
		{'SLS', 2, 'Somaliland shilling'                     , 'Sl'},
		{'SOS', 2, 'Somali shilling'                         , 'Sh'},
		{'SRD', 2, 'Surinamese dollar'                       , '$'},
		{'SSP', 2, 'South Sudanese pound'                    , '£'},
		{'STN', 0, 'São Tomé and Príncipe dobra'             , 'Db'},
		{'SYP', 2, 'Syrian pound'                            , '£'},
		{'SZL', 2, 'Swazi lilangeni'                         , 'L'},
		{'THB', 2, 'Thai baht'                               , '฿'},
		{'TJS', 2, 'Tajikistani somoni'                      , 'с'},
		{'TMT', 2, 'Turkmenistan manat'                      , 'm'},
		{'TND', 3, 'Tunisian dinar'                          , 'د.ت'},
		{'TOP', 2, 'Tongan paʻanga'                           , 'T$'},
		{'TRY', 2, 'Turkish lira'                            , '₺'},
		{'TTD', 2, 'Trinidad and Tobago dollar'              , '$'},
		{'TVD', 2, 'Tuvaluan dollar'                         , '$'},
		{'TWD', 2, 'New Taiwan dollar'                       , '$'},
		{'TZS', 2, 'Tanzanian shilling'                      , 'Sh'},
		{'UAH', 2, 'Ukrainian hryvnia'                       , '₴'},
		{'UGX', 2, 'Ugandan shilling'                        , 'Sh'},
		{'USD', 2, 'United States dollar'                    , '$'},
		{'UYU', 2, 'Uruguayan peso'                          , '$'},
		{'UZS', 2, 'Uzbekistani soʻm'                         , 'Sʻ'},
		{'VES', 2, 'Venezuelan bolívar soberano'             , 'Bs'},
		{'VND', 0, 'Vietnamese đồng'                         , '₫'},
		{'VUV', 0, 'Vanuatu vatu'                            , 'Vt'},
		{'WST', 2, 'Samoan tālā'                             , 'T'},
		{'XAF', 0, 'Central African CFA franc'               , 'Fr'},
		{'XCD', 2, 'Eastern Caribbean dollar'                , '$'},
		{'XOF', 0, 'West African CFA franc'                  , 'Fr'},
		{'XPF', 0, 'CFP franc'                               , '₣'},
		{'YER', 2, 'Yemeni rial'                             , '﷼'},
		{'ZAR', 2, 'South African rand'                      , 'R'},
		{'ZMW', 2, 'Zambian kwacha'                          , 'ZK'},
		{'VEB', 0, 'Venezuelan bolívar'                      , 'BsD'},
	}

	tables.country = {
		country     , country, not_null, pk,
		lang        , lang, not_null, fk,
		currency    , currency, fk,
		imperial_system, bool0,
		week_start_offset, int8, not_null, --Sun:0, Mon:1, Sat:-1, Fri:-2
		en_name     , name, not_null,
	}
	tables.country.name_col = 'en_name'

	--https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
	--https://wiki.openstreetmap.org/wiki/Nominatim/Country_Codes
	--https://unece.org/fileadmin/DAM/cefact/recommendations/bkup_htm/cocucod1.htm
	tables.country.rows = {
		{'AD', 'ca', 'EUR', false,  1, 'Andorra'},
		{'AE', 'ar', 'AED', false, -1, 'United Arab Emirates'},
		{'AF', 'fa', 'AFN', false, -1, 'Afghanistan'},
		{'AG', 'en', 'XCD', false,  0, 'Antigua and Barbuda'},
		{'AI', 'en', 'XCD', false,  1, 'Anguilla'},
		{'AL', 'sq', 'ALL', false,  1, 'Albania'},
		{'AM', 'hy', 'AMD', false,  1, 'Armenia'},
		{'AO', 'pt', 'AOA', false,  1, 'Angola'},
		{'AQ', 'en', null , false,  1, 'Antarctica'},
		{'AR', 'es', 'ARS', false,  1, 'Argentina'},
		{'AS', 'en', 'USD', false,  0, 'American Samoa'},
		{'AT', 'de', 'EUR', false,  1, 'Austria'},
		{'AU', 'en', 'AUD', false,  0, 'Australia'},
		{'AW', 'nl', 'AWG', false,  1, 'Aruba'},
		{'AX', 'sv', null , false,  1, 'Åland Islands'},
		{'AZ', 'az', 'AZN', false,  1, 'Azerbaijan'},
		{'BA', 'bs', 'BAM', false,  1, 'Bosnia and Herzegovina'},
		{'BB', 'en', 'BBD', false,  1, 'Barbados'},
		{'BD', 'bn', 'BDT', false,  0, 'Bangladesh'},
		{'BE', 'nl', 'EUR', false,  1, 'Belgium'},
		{'BF', 'fr', 'XOF', false,  1, 'Burkina Faso'},
		{'BG', 'bg', 'BGN', false,  1, 'Bulgaria'},
		{'BH', 'ar', 'BHD', false,  1, 'Bahrain'},
		{'BI', 'fr', 'BIF', false,  1, 'Burundi'},
		{'BJ', 'fr', 'XOF', false,  1, 'Benin'},
		{'BL', 'fr', null , false,  1, 'Saint Barthélemy'},
		{'BM', 'en', 'BMD', false,  1, 'Bermuda'},
		{'BN', 'ms', 'BND', false,  1, 'Brunei Darussalam'},
		{'BO', 'es', 'BOB', false,  1, 'Bolivia'},
		{'BQ', 'nl', null , false,  1, 'Bonaire'},
		{'BR', 'pt', 'BRL', false,  0, 'Brazil'},
		{'BS', 'en', 'BSD', false,  0, 'Bahamas'},
		{'BT', 'dz', 'INR', false,  0, 'Bhutan'},
		{'BV', 'no', 'NOK', false,  1, 'Bouvet Island'},
		{'BW', 'en', 'BWP', false,  0, 'Botswana'},
		{'BY', 'be', 'BYN', false,  1, 'Belarus'},
		{'BZ', 'en', 'BZD', false,  0, 'Belize'},
		{'CA', 'en', 'CAD', false,  0, 'Canada'},
		{'CC', 'en', 'AUD', false,  1, 'Cocos Islands'},
		{'CD', 'fr', 'CDF', false,  1, 'Congo, the Democratic Republic of the'},
		{'CF', 'fr', 'XAF', false,  1, 'Central African Republic'},
		{'CG', 'fr', 'XAF', false,  1, 'Congo'},
		{'CH', 'de', 'CHF', false,  1, 'Switzerland'},
		{'CI', 'fr', 'XOF', false,  1, 'Côte d\'Ivoire'},
		{'CK', 'en', 'NZD', false,  1, 'Cook Islands'},
		{'CL', 'es', 'CLP', false,  1, 'Chile'},
		{'CM', 'fr', 'XAF', false,  1, 'Cameroon'},
		{'CN', 'zh', 'CNY', false,  0, 'China'},
		{'CO', 'es', 'COP', false,  0, 'Colombia'},
		{'CR', 'es', 'CRC', false,  1, 'Costa Rica'},
		{'CU', 'es', 'CUP', false,  1, 'Cuba'},
		{'CV', 'pt', 'CVE', false,  1, 'Cape Verde'},
		{'CW', 'nl', 'ANG', false,  1, 'Curaçao'},
		{'CX', 'en', 'AUD', false,  1, 'Christmas Island'},
		{'CY', 'el', 'EUR', false,  1, 'Cyprus'},
		{'CZ', 'cs', 'CZK', false,  1, 'Czech Republic'},
		{'DE', 'de', 'EUR', false,  1, 'Germany'},
		{'DJ', 'fr', 'DJF', false, -1, 'Djibouti'},
		{'DK', 'da', 'DKK', false,  1, 'Denmark'},
		{'DM', 'en', 'XCD', false,  0, 'Dominica'},
		{'DO', 'es', 'DOP', false,  0, 'Dominican Republic'},
		{'DZ', 'ar', 'DZD', false, -1, 'Algeria'},
		{'EC', 'es', 'USD', false,  1, 'Ecuador'},
		{'EE', 'et', 'EUR', false,  1, 'Estonia'},
		{'EG', 'ar', 'EGP', false, -1, 'Egypt'},
		{'EH', 'ar', 'MAD', false,  1, 'Western Sahara'},
		{'ER', 'ti', 'ERN', false,  1, 'Eritrea'},
		{'ES', 'as', 'EUR', false,  1, 'Spain'},
		{'ET', 'am', 'ETB', false,  0, 'Ethiopia'},
		{'FI', 'fi', 'EUR', false,  1, 'Finland'},
		{'FJ', 'en', 'FJD', false,  1, 'Fiji'},
		{'FK', 'en', 'FKP', false,  1, 'Falkland Islands'},
		{'FM', 'en', 'USD', false,  1, 'Micronesia'},
		{'FO', 'fo', 'FOK', false,  1, 'Faroe Islands'},
		{'FR', 'fr', 'EUR', false,  1, 'France'},
		{'GA', 'fr', 'XAF', false,  1, 'Gabon'},
		{'GB', 'en', 'GBP', false,  1, 'United Kingdom'},
		{'GD', 'en', 'XCD', false,  1, 'Grenada'},
		{'GE', 'ka', 'GEL', false,  1, 'Georgia'},
		{'GF', 'fr', 'EUR', false,  1, 'French Guiana'},
		{'GG', 'en', 'GBP', false,  1, 'Guernsey'},
		{'GH', 'en', 'GHS', false,  1, 'Ghana'},
		{'GI', 'en', 'GIP', false,  1, 'Gibraltar'},
		{'GL', 'kl', 'DKK', false,  1, 'Greenland'},
		{'GM', 'en', 'GMD', false,  1, 'Gambia'},
		{'GN', 'fr', 'GNF', false,  1, 'Guinea'},
		{'GP', 'fr', 'EUR', false,  1, 'Guadeloupe'},
		{'GQ', 'es', 'XAF', false,  1, 'Equatorial Guinea'},
		{'GR', 'el', 'EUR', false,  1, 'Greece'},
		{'GS', 'en', null , false,  1, 'South Georgia and the South Sandwich Islands'},
		{'GT', 'es', 'GTQ', false,  0, 'Guatemala'},
		{'GU', 'en', 'USD', false,  0, 'Guam'},
		{'GW', 'pt', 'XOF', false,  1, 'Guinea-Bissau'},
		{'GY', 'en', 'GYD', false,  1, 'Guyana'},
		{'HK', 'zh', 'HKD', false,  0, 'Hong Kong'},
		{'HM', 'en', 'AUD', false,  1, 'Heard Island and McDonald Islands'},
		{'HN', 'es', 'HNL', false,  0, 'Honduras'},
		{'HR', 'hr', 'HRK', false,  1, 'Croatia'},
		{'HT', 'fr', 'HTG', false,  1, 'Haiti'},
		{'HU', 'hu', 'HUF', false,  1, 'Hungary'},
		{'ID', 'id', 'IDR', false,  0, 'Indonesia'},
		{'IE', 'en', 'EUR', false,  1, 'Ireland'},
		{'IL', 'he', 'ILS', false,  0, 'Israel'},
		{'IM', 'en', 'GBP', false,  1, 'Isle of Man'},
		{'IN', 'hi', 'INR', false,  0, 'India'},
		{'IO', 'en', 'USD', false,  1, 'British Indian Ocean Territory'},
		{'IQ', 'ar', 'IQD', false, -1, 'Iraq'},
		{'IR', 'fa', 'IRR', false, -1, 'Iran'},
		{'IS', 'is', 'ISK', false,  1, 'Iceland'},
		{'IT', 'it', 'EUR', false,  1, 'Italy'},
		{'JE', 'en', 'GBP', false,  1, 'Jersey'},
		{'JM', 'en', 'JMD', false,  0, 'Jamaica'},
		{'JO', 'ar', 'JOD', false, -1, 'Jordan'},
		{'JP', 'ja', 'JPY', false,  0, 'Japan'},
		{'KE', 'sw', 'KES', false,  0, 'Kenya'},
		{'KG', 'ky', 'KGS', false,  1, 'Kyrgyzstan'},
		{'KH', 'km', 'KHR', false,  0, 'Cambodia'},
		{'KI', 'en', 'AUD', false,  1, 'Kiribati'},
		{'KM', 'ar', 'KMF', false,  1, 'Comoros'},
		{'KN', 'en', 'XCD', false,  1, 'Saint Kitts and Nevis'},
		{'KP', 'ko', 'KPW', false,  1, 'Korea, North'},
		{'KR', 'ko', 'KRW', false,  0, 'Korea, South'},
		{'KW', 'ar', 'KWD', false, -1, 'Kuwait'},
		{'KY', 'en', 'KYD', false,  1, 'Cayman Islands'},
		{'KZ', 'kk', 'KZT', false,  1, 'Kazakhstan'},
		{'LA', 'lo', 'LAK', false,  0, 'Lao'},
		{'LB', 'ar', 'LBP', false,  1, 'Lebanon'},
		{'LC', 'en', 'XCD', false,  1, 'Saint Lucia'},
		{'LI', 'de', 'CHF', false,  1, 'Liechtenstein'},
		{'LK', 'si', 'LKR', false,  1, 'Sri Lanka'},
		{'LR', 'en', 'LRD', true ,  1, 'Liberia'},
		{'LS', 'en', 'ZAR', false,  1, 'Lesotho'},
		{'LT', 'lt', 'EUR', false,  1, 'Lithuania'},
		{'LU', 'lb', 'EUR', false,  1, 'Luxembourg'},
		{'LV', 'lv', 'EUR', false,  1, 'Latvia'},
		{'LY', 'ar', 'LYD', false, -1, 'Libya'},
		{'MA', 'fr', 'MAD', false,  1, 'Morocco'},
		{'MC', 'fr', 'EUR', false,  1, 'Monaco'},
		{'MD', 'ro', 'MDL', false,  1, 'Moldova'},
		{'ME', 'sr', 'EUR', false,  1, 'Montenegro'},
		{'MF', 'fr', null , false,  1, 'Saint Martin (French part}'},
		{'MG', 'mg', 'MGA', false,  1, 'Madagascar'},
		{'MH', 'en', 'USD', false,  0, 'Marshall Islands'},
		{'MK', 'mk', 'MKD', false,  1, 'Macedonia'},
		{'ML', 'fr', 'XOF', false,  1, 'Mali'},
		{'MM', 'my', 'MMK', true ,  0, 'Myanmar'},
		{'MN', 'mn', 'MNT', false,  1, 'Mongolia'},
		{'MO', 'zh', 'MOP', false,  0, 'Macao'},
		{'MP', 'en', 'USD', false,  1, 'Northern Mariana Islands'},
		{'MQ', 'fr', 'EUR', false,  1, 'Martinique'},
		{'MR', 'ar', 'MRU', false,  1, 'Mauritania'},
		{'MS', 'en', 'XCD', false,  1, 'Montserrat'},
		{'MT', 'mt', 'EUR', false,  0, 'Malta'},
		{'MU', 'en', 'MUR', false,  1, 'Mauritius'},
		{'MV', 'dv', 'MVR', false, -2, 'Maldives'},
		{'MW', 'en', 'MWK', false,  1, 'Malawi'},
		{'MX', 'es', 'MXN', false,  0, 'Mexico'},
		{'MY', 'ms', 'MYR', false,  1, 'Malaysia'},
		{'MZ', 'pt', 'MZN', false,  0, 'Mozambique'},
		{'NA', 'en', 'ZAR', false,  1, 'Namibia'},
		{'NC', 'fr', 'XPF', false,  1, 'New Caledonia'},
		{'NE', 'fr', 'XOF', false,  1, 'Niger'},
		{'NF', 'en', 'AUD', false,  1, 'Norfolk Island'},
		{'NG', 'en', 'NGN', false,  1, 'Nigeria'},
		{'NI', 'es', 'NIO', false,  0, 'Nicaragua'},
		{'NL', 'nl', 'EUR', false,  1, 'Netherlands'},
		{'NO', 'no', 'NOK', false,  1, 'Norway'},
		{'NP', 'ne', 'NPR', false,  0, 'Nepal'},
		{'NR', 'na', 'AUD', false,  1, 'Nauru'},
		{'NU', 'en', 'NZD', false,  1, 'Niue'},
		{'NZ', 'mi', 'NZD', false,  1, 'New Zealand'},
		{'OM', 'ar', 'OMR', false, -1, 'Oman'},
		{'PA', 'es', 'USD', false,  0, 'Panama'},
		{'PE', 'es', 'PEN', false,  0, 'Peru'},
		{'PF', 'fr', 'XPF', false,  1, 'French Polynesia'},
		{'PG', 'en', 'PGK', false,  1, 'Papua New Guinea'},
		{'PH', 'en', 'PHP', false,  0, 'Philippines'},
		{'PK', 'en', 'PKR', false,  0, 'Pakistan'},
		{'PL', 'pl', 'PLN', false,  1, 'Poland'},
		{'PM', 'fr', 'EUR', false,  1, 'Saint Pierre and Miquelon'},
		{'PN', 'en', 'NZD', false,  1, 'Pitcairn'},
		{'PR', 'es', 'USD', false,  0, 'Puerto Rico'},
		{'PS', 'ar', null , false,  1, 'Palestine'},
		{'PT', 'pt', 'EUR', false,  0, 'Portugal'},
		{'PW', 'en', 'USD', false,  1, 'Palau'},
		{'PY', 'es', 'PYG', false,  0, 'Paraguay'},
		{'QA', 'ar', 'QAR', false, -1, 'Qatar'},
		{'RE', 'fr', 'EUR', false,  1, 'Réunion'},
		{'RO', 'ro', 'RON', false,  1, 'Romania'},
		{'RS', 'sr', 'RSD', false,  1, 'Serbia'},
		{'RU', 'ru', 'RUB', false,  1, 'Russian Federation'},
		{'RW', 'rw', 'RWF', false,  1, 'Rwanda'},
		{'SA', 'ar', 'SAR', false,  0, 'Saudi Arabia'},
		{'SB', 'en', 'SBD', false,  1, 'Solomon Islands'},
		{'SC', 'fr', 'SCR', false,  1, 'Seychelles'},
		{'SD', 'ar', 'SDG', false, -1, 'Sudan'},
		{'SE', 'sv', 'SEK', false,  1, 'Sweden'},
		{'SG', 'zh', 'BND', false,  0, 'Singapore'},
		{'SH', 'en', 'SHP', false,  1, 'Saint Helena'},
		{'SI', 'sl', 'EUR', false,  1, 'Slovenia'},
		{'SJ', 'no', 'NOK', false,  1, 'Svalbard and Jan Mayen'},
		{'SK', 'sk', 'EUR', false,  1, 'Slovakia'},
		{'SL', 'en', 'SLL', false,  1, 'Sierra Leone'},
		{'SM', 'it', 'EUR', false,  1, 'San Marino'},
		{'SN', 'fr', 'XOF', false,  1, 'Senegal'},
		{'SO', 'so', 'SOS', false,  1, 'Somalia'},
		{'SR', 'nl', 'SRD', false,  1, 'Suriname'},
		{'SS', 'en', 'SSP', false,  1, 'South Sudan'},
		{'ST', 'pt', 'STN', false,  1, 'Sao Tome and Principe'},
		{'SV', 'es', 'USD', false,  0, 'El Salvador'},
		{'SX', 'nl', null , false,  1, 'Sint Maarten (Dutch part}'},
		{'SY', 'ar', 'SYP', false, -1, 'Syria'},
		{'SZ', 'en', 'SZL', false,  1, 'Swaziland'},
		{'TC', 'en', 'USD', false,  1, 'Turks and Caicos Islands'},
		{'TD', 'fr', 'XAF', false,  1, 'Chad'},
		{'TF', 'fr', 'EUR', false,  1, 'French Southern Territories'},
		{'TG', 'fr', 'XOF', false,  1, 'Togo'},
		{'TH', 'th', 'THB', false,  0, 'Thailand'},
		{'TJ', 'tg', 'TJS', false,  1, 'Tajikistan'},
		{'TK', 'tk', 'NZD', false,  1, 'Tokelau'},
		{'TL', 'pt', 'USD', false,  1, 'Timor-Leste'},
		{'TM', 'tk', 'TMT', false,  1, 'Turkmenistan'},
		{'TN', 'ar', 'TND', false,  1, 'Tunisia'},
		{'TO', 'en', 'TOP', false,  1, 'Tonga'},
		{'TR', 'tr', 'TRY', false,  1, 'Turkey'},
		{'TT', 'en', 'TTD', false,  0, 'Trinidad and Tobago'},
		{'TV', 'en', 'AUD', false,  1, 'Tuvalu'},
		{'TW', 'zh', 'TWD', false,  0, 'Taiwan'},
		{'TZ', 'sw', 'TZS', false,  1, 'Tanzania'},
		{'UA', 'uk', 'UAH', false,  1, 'Ukraine'},
		{'UG', 'en', 'UGX', false,  1, 'Uganda'},
		{'UM', 'en', 'USD', false,  0, 'United States Minor Outlying Islands'},
		{'US', 'en', 'USD', true ,  0, 'United States'},
		{'UY', 'es', 'UYU', false,  1, 'Uruguay'},
		{'UZ', 'uz', 'UZS', false,  1, 'Uzbekistan'},
		{'VA', 'it', 'EUR', false,  1, 'Vatican'},
		{'VC', 'en', 'XCD', false,  1, 'Saint Vincent and the Grenadines'},
		{'VE', 'es', 'VEB', false,  0, 'Venezuela'},
		{'VG', 'en', 'USD', false,  1, 'Virgin Islands, British'},
		{'VI', 'en', 'USD', false,  0, 'Virgin Islands, U.S.'},
		{'VN', 'vi', 'VND', false,  1, 'Viet Nam'},
		{'VU', 'bi', 'VUV', false,  1, 'Vanuatu'},
		{'WF', 'fr', 'XPF', false,  1, 'Wallis and Futuna'},
		{'WS', 'sm', 'WST', false,  0, 'Samoa'},
		{'YE', 'ar', 'YER', false,  0, 'Yemen'},
		{'YT', 'fr', 'EUR', false,  1, 'Mayotte'},
		{'ZA', 'en', 'ZAR', false,  0, 'South Africa'},
		{'ZM', 'en', 'ZMW', false,  1, 'Zambia'},
		{'ZW', 'en',  null, false,  0, 'Zimbabwe'},
	}

end

local supported_langs = glue.memoize(function()
	local t = {}
	for i,row in each_row'select * from lang where supported = 1' do
		t[row.lang] = row
	end
	return t
end)

local supported_countries = glue.memoize(function()
	local t = {}
	for i,row in each_row'select * from country' do
		t[row.country] = row
	end
	return t
end)

webb.langinfo = setmetatable({}, {__index = function(t, k)
	return supported_langs()[k]
end})

webb.countryinfo = setmetatable({}, {__index = function(t, k)
	return supported_countries()[k]
end})

qmacro.lang = function()
	return sqlval(lang())
end

qmacro.default_lang = function()
	return sqlval(default_lang())
end

return webb.lang_schema --so you can call schema:import'webb_lang'
