--[==[

	webb | session-based authentication
	Written by Cosmin Apreutesei. Public Domain.

API
	[try_]login([auth][, switch_user]) -> realusr   login and set lang (if not set)
	usr([field|'*']) -> val | t | usr         login and get current user field(s) or id
	tenant()                                  get current tenant
	touch_usr([usr])                          update (current) user's atime
	gen_auth_token(email) -> token            generate a one-time long-lived auth token
	gen_auth_code('email', email) -> code     generate a one-time short-lived auth code
	gen_auth_code('phone', phone) -> code     generate a one-time short-lived auth code
	usr_[create|update|create_or_update]({k->v}) -> usr    create and/or update a user
	usr_delete(usr)                           delete a user

SCHEMA
	auth_schema                              auth schema

CONFIG
	auth_storage        'fs'           auth backend: 'fs' or 'sql'
	allow_create_user   true           allow creating new users on auth
	auto_create_user    true           auto-create anonymous users
	auth_token_lifetime 3600           forgot-password token lifetime (seconds)
	auth_token_maxcount 2              max unexpired tokens allowed
	auth_code_lifetime  300            one-time auth code lifetime (seconds)
	auth_code_maxcount  6              max unexpired auth codes allowed

API --------------------------------------------------------------------------

	[try_]login([auth][, switch_user]) -> usr

	Login using an auth object (see below).

[real]usr() -> usr

	Get the current user id. Same as calling `login()` without args.

[real]usr(field) -> v

	Get the value of a specific field from the user info.

[real]usr'*' -> t

	Get full user info.

touch_usr()

	Update user's access time. Call it on every request as a way of tracking
	user activity, eg. for knowing when to send those annoying "forgot items
	in your cart" emails.

gen_auth_token(email) -> token

	Generate a long-lived authentication token to be put in a link and sent
	in a forgot-password email, and used once with 'token' auth type.
	Using it also validates the email that it was generated for.
	Errors:
		'email_not_found' - no account with this email.
		'too_many_tokens' - auth_token_maxcount limit reached.

gen_auth_code('email', email) -> code
gen_auth_code('phone', phone) -> code

	Generate a 6-digit short-lived authentication code to be sent via
	email or phone and be used back once with 'code' auth type.
	If there's no user account with that email/phone, a new one is created.
	Using it also validates the phone or email that it was generated for.
	Errors:
		'too_many_tokens' - auth_code_maxcount limit reached.

AUTH OBJECT

{type = 'session'}

	login using session cookie (default). if there's no session cookie
	or it's invalid, an anonymous user is created subject to auto_create_user.

{type = 'logout'}

	Clears the session cookie and creates an anonymous user and returns it.

{type = 'anonymous'}

	login using session cookie but logout and create an anonymous user
	if the logged in user is not anonymous.

{type = 'pass', action = 'login', email = , pass = }

	login to an existing user using its email and password.
	errors:
		'user_pass' - the email or password is wrong.

{type = 'pass', action = 'create', email = , pass = }

	create a user with a password and login to it.
	errors:
		'email_taken' - email already used on another account.

{type = 'nopass', email = }

	login using only user.

{type = 'update', email = , phone = , pass = , name = }

	update the info of the currently logged in user.
	errors:
		'email_taken' - email already used on another account.
		'phone_taken' - phone already used on another account.

{type = 'token', token = }

	login using a temporary token that was generated by a remember password
	form. a token can be used only once.
	errors:
		'invalid_token'` - token was not found or expired.

{type = 'code', code = }

	login using a temporary 6-digit code that was generated by a sign-in form.
	a sign-in code can be used only once.
	errors:
		'invalid_code' - code was not found or expired.

USER SWITCHING

Regardless of how the user is authenticated, the session cookie is
updated and it will be sent with the reply. If there was already a user
logged in before and it was a different user, the callback
`switch_user(new_usr, old_usr)` is called. If that previous user was
anonymous then that user is also deleted afterwards.

]==]

require'webb'
require'glue'
require'schema'
require'bcrypt'
require'http_date'

local function use_sql()
	return config('auth_storage', 'fs') == 'sql'
end

--schema ---------------------------------------------------------------------

function auth_schema()

	import'schema_std'

	tables.tenant = {
		tenant      , idpk,
		name        , name,
		host        , name,
		active      , bool1,
		ctime       , ctime,
	}

	tables.usr = {
		usr         , idpk    ,
		tenant      , id      , not_null, fk,
		anonymous   , bool1   ,
		email       , email   , uk,
		emailvalid  , bool0   ,
		pass        , hash    ,
		active      , bool1   ,
		title       , name    ,
		name        , name    ,
		phone       , strid   ,
		phonevalid  , bool0   ,
		sex         , enum'M F O',
		birthday    , date    ,
		newsletter  , bool0   ,
		roles       , text    ,
		note        , text    ,
		theme       , strid   ,
		clientip    , strid   , --when it was created
		atime       , atime   , --last access time
		ctime       , ctime   , --creation time
		mtime       , mtime   , --last modification time
	}

	tables.sess = {
		token       , hash   , not_null, pk,
		usr         , id     , not_null, child_fk,
		expires     , time   , not_null,
		clientip    , strid  , --when it was created
		ctime       , ctime  ,
	}

	tables.usrtoken = {
		token       , hash   , not_null, pk,
		usr         , id     , not_null, child_fk,
		expires     , time   , not_null,
		validates   , enum'email phone', not_null,
		ctime       , ctime  ,
	}

	if _G.multilang() then

		import'lang'

		add_cols('usr after note', {
			lang        , lang    , weak_fk,
			country     , country , weak_fk,
		})

	end

end

--fs storage -----------------------------------------------------------------

local function check_path_safe(s)
	assert(not s:find'[/\\%z]', 'invalid chars')
	assert(s ~= '.' and s ~= '..', 'invalid path')
end

local function email_path(email)
	email = email:lower()
	check_path_safe(email)
	return varpath('email', email)
end

local function phone_path(phone)
	check_path_safe(phone)
	return varpath('phone', phone)
end

local function fs_load_usr(usr)
	local s = load(varpath('usr', usr, 'data'))
	if s == nil then return nil end
	local t = eval(s)
	assert(istab(t))
	t.usr = usr
	return t
end

local function fs_update_usr(usr, updates)
	local old = fs_load_usr(usr) or {}
	local new = update({}, old, updates)
	if old.email ~= new.email then
		if old.email and new.email then
			rename(email_path(old.email), email_path(new.email))
		elseif old.email then
			rmfile(email_path(old.email))
		else
			save(email_path(new.email), tostring(usr))
		end
	end
	if old.phone ~= new.phone then
		if old.phone and new.phone then
			rename(phone_path(old.phone), phone_path(new.phone))
		elseif old.phone then
			rmfile(phone_path(old.phone))
		else
			save(phone_path(new.phone), tostring(usr))
		end
	end
	save(varpath('usr', usr, 'data'), pp(new))
end

local function fs_email_usr(email)
	local s = load(email_path(email))
	return s and tonumber(s:trim())
end

local function fs_phone_usr(phone)
	local s = load(phone_path(phone))
	return s and tonumber(s:trim())
end

local function fs_token_path(token_hash)
	return varpath('usrtoken', token_hash)
end

local function fs_usr_token_path(usr, validates, token_hash)
	return varpath('usr', usr, 'token_'..validates..'_'..token_hash)
end

local function fs_token_gc_and_count(usr, validates)
	local now = time()
	local dir_path = varpath('usr', usr)
	local prefix = 'token_'..validates..'_'
	local count = 0
	for name, d in ls(dir_path) do
		if not name then break end
		if d:is'file' and name:starts(prefix) then
			local token_hash = name:sub(#prefix + 1)
			local marker_path = indir(dir_path, name)
			local expires = tonumber(load(marker_path))
			if not expires or expires <= now then
				rmfile(marker_path)
				rmfile(fs_token_path(token_hash))
			else
				count = count + 1
			end
		end
	end
	return count
end

local function fs_delete_token(token_hash)
	local s = load(fs_token_path(token_hash))
	if not s then return end
	local t = eval(s)
	if t then
		rmfile(fs_usr_token_path(t.usr, t.validates, token_hash))
	end
	rmfile(fs_token_path(token_hash))
end

--session cookie -------------------------------------------------------------

local function load_session()
	local s = headers('cookie'); if not s then return end
	local sid = s:match'^session=([^;]*)' or s:match'; *session=([^;]*)'
	if not sid or sid == '' then return end
	if sid:find'[^%x]' then return end --hex chars only
	local now = time()
	local usr
	if use_sql() then
		usr = first_row_vals([[
			select usr
			from sess where token = ? and expires > ?
			]], sid, now)
	else
		local s = load(varpath('sess', sid))
		local t = s and eval(s)
		usr = t and t.expires > now and t.usr
	end
	if not usr then return end
	return {id = sid, usr = usr}
end
local session = http_once_per_request(function()
	return load_session() or {}
end)

local function session_usr()
	return session().usr
end

local function save_session(sess)
	local secure_flag = scheme'https'
	sess.expires = sess.expires or time() + 2 * 365 * 24 * 3600 --2 years
	if sess.usr then --login
		if not sess.id then
			sess.id = tohex(random_string(16))
			if use_sql() then
				query([[
					insert into sess
						(token, expires, usr)
					values
						(?, ?, ?)
					]],
					sess.id,
					sess.expires,
					sess.usr
				)
			else
				save(varpath('sess', sess.id), pp({
					expires = sess.expires,
					usr = sess.usr,
				}))
			end
		else
			if use_sql() then
				query([[
					update sess set
						usr = ?,
						expires = ?
					where
						token = ?
					]], sess.usr, sess.expires, sess.id)
			else
				save(varpath('sess', sess.id), pp({
					expires = sess.expires,
					usr = sess.usr,
				}))
			end
		end
		setheader('set-cookie',
			'session='..sess.id
			..'; Path=/'
			..'; Expires='..http_date_format(sess.expires)
			..(secure_flag and '; Secure' or '') --prevent MITM
			..'; HttpOnly' --prevent JS access
			..'; SameSite='..(secure_flag and 'strict' or 'lax') --prevent BREACH (but also img tracking)
		)
	elseif sess.id then --logout
		if use_sql() then
			query('delete from sess where token = ?', sess.id)
		else
			rmfile(varpath('sess', sess.id))
		end
		sess.id = nil
		setheader('set-cookie',
			'session=0'
			..'; Path=/'
			..'; Expires=Thu, 01 Jan 1970 00:00:00 GMT'
			..(secure_flag and '; Secure' or '')
			..'; HttpOnly'
			..'; SameSite=strict'
		)
	end
end

local function save_usr(usr)
	local sess = session()
	if not sess.id or sess.usr ~= usr then
		sess.usr = usr
		save_session(sess)
	end
end

--authentication frontend ----------------------------------------------------

local auth = {} --auth.<type>(auth) -> usr, can_create

local function authenticate(a)
	local auth = auth[a and istab(a) and a.type or 'session']
	if not auth then
		return nil, 'invalid argument'
	end
	log('', 'auth', 'auth', '%s', a)
	local usr, err = auth(a)
	if usr then
		log('', 'auth', 'auth-ok', 'usr=%d', usr)
		return usr
	else
		log('', 'auth', 'auth-fail', '%s', err)
		return nil, err
	end
end

local weak_vals_mt = {__mode = 'v'}

local userinfo = http_once_per_request(function(usr)
	local t
	if usr then
		if use_sql() then
			t = first_row([[
				select
					usr,
					tenant,
					anonymous,
					email,
					emailvalid,
					if(pass is not null, 1, 0) as haspass,
					roles,
					name,
					phone,
					phonevalid,
					#if multilang()
					lang,
					country,
					#endif
					theme,
					atime,
					ctime,
					mtime
				from
					usr
				where
					active = 1 and usr = ?
				]], usr)
		else
			local s = load(varpath('usr', usr, 'data'))
			t = s and eval(s)
			if t then
				t.usr = usr
				t.haspass = t.pass and 1 or 0
				t.pass = nil --prevent leaking it
				t.atime = file_attr(varpath('usr', usr, 'data'), 'atime')
				if not t.active then t = nil end
			end
		end
	end
	if not t then
		return {roles = {}}
	end
	t.haspass = tonumber(t.haspass) == 1
	t.roles = index(collect(words(t.roles or {})))
	t.admin = t.roles.admin
	t.sessions = setmetatable({}, weak_vals_mt)
	return t
end)

--session-cookie authentication ----------------------------------------------

local function valid_usr(usr)
	return userinfo(usr).usr
end

local function anonymous_usr(usr)
	return userinfo(usr).anonymous and usr
end

local function create_user()
	allow(config('allow_create_user', true))
	wait(0.2) --make flooding up the table a bit slower
	local usr
	if use_sql() then
		atomic(function()
			local tenant = check500(first_row([[
				select tenant from tenant where host = ?
			]], host()), 'no tenant for host %s', host())

			usr = query([[
				insert into usr set
					tenant = :tenant,
					clientip = :clientip,
					#if multilang()
					lang = :lang,
					#endif
					atime = now(),
					ctime = now(),
					mtime = now()
			]], {
				tenant = tenant,
				clientip = client_ip(),
				lang = lang(),
			}).insert_id

			session().usr = usr
		end)
	else
		local tenant = check500(load(varpath('tenant', host())),
			'no tenant for host %s', host())

		usr = gen_id('usr')
		save(varpath('usr', usr, 'data'), pp({
			tenant = tenant,
			clientip = client_ip(),
			lang = multilang() and lang(),
			active = true,
			anonymous = true,
		}))
		session().usr = usr
	end

	return usr
end

function auth.session()
	local usr = valid_usr(session_usr())
	if not usr then
		if not config('auto_create_user', true) then
			return nil, 'session auth failed'
		end
		return create_user()
	end
	return usr
end

function auth.logout()
	save_usr(nil)
	return auth.session()
end

--anonymous authentication ---------------------------------------------------

function auth.anonymous()
	return anonymous_usr(session_usr()) or create_user()
end

--password authentication ----------------------------------------------------

local function email_pass_usr(email, pass)
	if use_sql() then
		local u = first_row([[
			select u.usr, u.pass
			from usr u
			left join tenant t on t.tenant = u.tenant
			where
				u.active = 1
				and coalesce(t.active, 1) = 1
				and u.email = ?
			]], email)
		return u and u.pass and bcrypt_verify(pass, u.pass) and u.usr or nil
	else
		local usr = fs_email_usr(email)
		if not usr then return nil end
		local t = fs_load_usr(usr)
		if not t or not t.active then return nil end
		return t.pass and bcrypt_verify(pass, t.pass) and usr or nil
	end
end

local function email_usr(email)
	if use_sql() then
		return first_row([[
			select usr from usr where
				email = ?
			]], email)
	else
		return fs_email_usr(email)
	end
end

local function phone_usr(phone)
	if use_sql() then
		return first_row([[
			select usr from usr where
				phone = ?
			]], phone)
	else
		return fs_phone_usr(phone)
	end
end

local function delete_user(usr)
	if use_sql() then
		query('delete from usr where usr = ?', usr)
	else
		local dir_path = varpath('usr', usr)
		for name, d in ls(dir_path) do
			if not name then break end
			if d:is'file' and name:starts'token_' then
				local token_hash = name:match'^token_[^_]+_(.+)$'
				if token_hash then rmfile(fs_token_path(token_hash)) end
			end
		end
		local t = fs_load_usr(usr)
		if t then
			if t.email then rmfile(email_path(t.email)) end
			if t.phone then rmfile(phone_path(t.phone)) end
		end
		rm_rf(dir_path)
	end
end

function usr_delete(usr_to_delete)
	if http_request() then
		local roles = usr'roles'
		allow(roles.dev or roles.admin, 'only devs and admins can remove users')
		allow(roles.dev or userinfo(usr_to_delete).tenant == tenant(), 'only devs can remove users of other tenants')
	end
	delete_user(usr_to_delete)
end

local function fs_usr_upsert(t)
	local usr = t.usr or gen_id('usr')
	t.active = t.active ~= nil and t.active or true
	fs_update_usr(usr, t)
	return usr
end

--RULE: 'admin' roles can only create and update users with the same tenant as them.
--RULE: 'dev' roles can create and update users with any tenant.
--RULE: 'admin' roles cannot create or update 'dev' roles.
local function usr_insert_or_update_args(t, dt)
	t = update(dt or {}, t)
	t.roles = isstr(t.roles) and index(collect(words(t.roles))) or t.roles
	if http_request() then
		local roles = usr'roles'
		t.tenant = t.tenant or tenant()
		allow(roles.admin or roles.dev, 'must be admin or dev to create or update user')
		allow(roles.dev or not t.roles.dev, 'only devs can create or update devs')
		allow(roles.dev or t.tenant == tenant(), 'only devs can create/move users of/to other tenants')
	end
	t.roles = t.roles ~= nil and cat(keys(t.roles, true), ' ') or nil
	return t
end

function usr_create(t)
	t = usr_insert_or_update_args(t, {anonymous = false})
	if use_sql() then return insert_row('usr', t) end
	return fs_usr_upsert(t)
end

function usr_update(t)
	t = usr_insert_or_update_args(t)
	if use_sql() then update_row('usr', t) return end
	assert(t.usr, 'usr required for update')
	fs_update_usr(t.usr, t)
end

function usr_create_or_update(t)
	t = usr_insert_or_update_args(t, {anonymous = false})
	if use_sql() then
		t.usr = insert_or_update_row('usr', t)
		return t.usr
	end
	return fs_usr_upsert(t)
end

--no-password authentication: enable only for debugging!
function auth.nopass(auth)
	if false then
		return first_row([[
			select u.usr
			from usr u
			left join tenant t on t.tenant = u.tenant
			where
				u.active = 1
				and coalesce(t.active, 1) = 1
				and email = ?
			]], auth.email)
	end
end

function auth.pass(auth)
	if auth.action == 'login' then
		local usr = email_pass_usr(auth.email, auth.pass)
		if not usr then
			return nil,
				S('invalid_email_or_pass', 'Invalid email or password'),
				'email_pass'
		else
			return usr
		end
	elseif auth.action == 'create' then
		local email = assert(json_str_arg(auth.email))
		assert(#email >= 1)
		local pass = assert(auth.pass)
		assert(isstr(pass) and #pass >= 1)
		if email_usr(email) then
			return nil,
				S('email_taken', 'Email already registered'),
				'email_taken'
		end
		local usr = anonymous_usr(session_usr()) or create_user()
		if use_sql() then
			query([[
				update usr set
					anonymous = 0,
					emailvalid = 0,
					email = ?,
					pass = ?
				where
					usr = ?
				]], email, bcrypt_hash(pass), usr)
		else
			fs_update_usr(usr, {
				anonymous  = false,
				emailvalid = false,
				email      = email,
				pass       = bcrypt_hash(pass),
			})
		end
		return usr
	end
end

--one-time token or code authentication --------------------------------------

local function register_token(usr, token, validates, token_lifetime, token_maxcount)

	local now = time()
	local expires = now + token_lifetime

	if use_sql() then
		--now it's a good time to garbage-collect expired tokens
		query('delete from usrtoken where expires <= from_unixtime(?)', now)

		--check if too many tokens were requested
		local n = first_row([[
			select count(1) from usrtoken where
				usr = ? and validates = ? and expires > from_unixtime(?)
			]], usr, validates, now)
		if tonumber(n) >= token_maxcount then
			return nil,
				S('too_many_tokens', 'Too many requests. Try again later.'),
				'too_many_tokens'
		end

		--add the token to db (break on collisions)
		query([[
			insert into usrtoken
				(token, usr, expires, validates, ctime)
			values
				(?, ?, ?, ?, ?)
			]], token, usr, expires, validates, now)
	else
		--gc expired tokens and count valid ones
		local n = fs_token_gc_and_count(usr, validates)
		if n >= token_maxcount then
			return nil,
				S('too_many_tokens', 'Too many requests. Try again later.'),
				'too_many_tokens'
		end

		save(fs_usr_token_path(usr, validates, token), tostring(expires))
		save(fs_token_path(token), pp({
			usr       = usr,
			expires   = expires,
			validates = validates,
			ctime     = now,
		}))
	end

	return true
end

function gen_auth_token(email)

	local token_lifetime = config('auth_token_lifetime', 60 * 60)
	local token_maxcount = config('auth_token_maxcount', 2)

	--find the user with this email
	local usr = email_usr(email)
	if not usr then
		return nil,
			S('email_not_found', 'Email not registered'),
			'email_not_found'
	end

	local token = tohex(random_string(32))
	local ok, err = register_token(usr, token, 'email', token_lifetime, token_maxcount)
	log('note', 'auth', 'gen-token', 'usr=%s token=%s'..(ok and '' or ' error=%s'), usr, token, err)
	return ok and token or nil, err
end

function gen_auth_code(validates, s)

	local code_lifetime = config('auth_code_lifetime', 10 * 60)
	local code_maxcount = config('auth_code_maxcount', 6)

	local usr
	if validates == 'email' then
		usr = email_usr(s)
		if not usr then
			usr = anonymous_usr(session_usr()) or create_user() --grab a new one
			if use_sql() then
				query('update usr set email = ? where usr = ?', s, usr)
			else
				fs_update_usr(usr, {email = s})
			end
		end
	elseif validates == 'phone' then
		usr = phone_usr(s)
		if not usr then
			usr = anonymous_usr(session_usr()) or create_user() --grab a new one
			if use_sql() then
				query('update usr set phone = ? where usr = ?', s, usr)
			else
				fs_update_usr(usr, {phone = s})
			end
		end
	else
		assert(false)
	end

	local code = ('%06d'):format(random(0, 999999))
	local ok, err = register_token(usr, code, validates, code_lifetime, code_maxcount)
	log('note', 'auth', 'gen-code', 'usr=%s code=%s validates=%s'..(ok and '' or ' error=%s'),
		usr, code, validates, err)
	return ok and code or nil, err
end

local function token_usr(token)
	if not token then return end
	wait(0.2) --slow down brute-forcing
	if use_sql() then
		local t = first_row([[
			select ut.usr, ut.validates from
				usrtoken ut
				inner join usr u on u.usr = ut.usr
				left join tenant t on t.tenant = u.tenant
			where
				u.active = 1
				and coalesce(t.active, 1) = 1
				and ut.expires > now()
				and ut.token = ?
			]], token)
		if not t then return end
		return t.usr, t.validates
	else
		local s = load(fs_token_path(token))
		if not s then return end
		local t = eval(s)
		if not t or t.expires <= time() then return end
		local u = fs_load_usr(t.usr)
		if not u or not u.active then return end
		return t.usr, t.validates
	end
end

--one-time short code authentication -----------------------------------------

local function auth_token(token, auth)
	--find the user
	local usr, validates = token_usr(token)
	if not usr then
		return nil,
			S('invalid_token', 'Invalid token'),
			'invalid_token'
	end

	if use_sql() then
		if validates == 'email' then
			query('update usr set emailvalid = 1, anonymous = 0 where usr = ?', usr)
		elseif validates == 'phone' then
			query('update usr set phonevalid = 1, anonymous = 0 where usr = ?', usr)
		end
		--remove the token because it's single use, and also to allow
		--the user to keep forgetting his password as much as he wants.
		query('delete from usrtoken where token = ?', token)
	else
		if validates == 'email' then
			fs_update_usr(usr, {emailvalid = true, anonymous = false})
		elseif validates == 'phone' then
			fs_update_usr(usr, {phonevalid = true, anonymous = false})
		end
		fs_delete_token(token)
	end

	return usr
end

function auth.token(auth)
	return auth_token(json_str_arg(auth.token))
end

function auth.code(auth)
	return auth_token(json_str_arg(auth.code))
end

--authentication logic -------------------------------------------------------

function try_login(auth, switch_user)
	switch_user = switch_user or pass
	local usr, err = authenticate(auth)
	if usr then
		local susr = valid_usr(session_usr())
		if susr and usr ~= susr then
			switch_user(usr, susr)
			if anonymous_usr(susr) then
				delete_user(susr)
				session().id = nil
				session().usr = nil
			end
		end
		save_usr(usr)
		local ui = userinfo(usr)
		setlang(ui.lang) --user lang has priority over action lang.
		setcountry(ui.country)
	end
	return usr, err
end
function login(...)
	return allow(try_login(...))
end

function realusr(attr)
	local usr = login()
	local t = userinfo(usr)
	if attr == '*' then
		return t
	elseif attr then
		return t[attr]
	else
		return usr
	end
end

function usr(attr)
	local realusr = login()
	local usr = args'usr' --impersonated user
	usr = usr and checkarg(id_arg(usr)) or realusr
	local u  = userinfo(usr)
	local ru = userinfo(realusr)
	if usr ~= realusr then
		allow(ru.roles.dev or (ru.roles.admin and ru.tenant == u.tenant),
			'user impersonation denied')
	end
	u.realusr = realusr
	u.realusr_roles = ru.roles
	if attr == '*' then
		return u
	elseif attr then
		return u[attr]
	else
		return usr
	end
end

function tenant()
	return usr'tenant'
end

function touch_usr(usr)
	--only touch usr on page requests
	if args(1) and args(1):find'%.' and not args(1):find'%.html$' then
		return
	end
	usr = usr or session_usr()
	if not usr then return end
	if use_sql() then
		query([[
			update usr set
				atime = now(), mtime = mtime
			where usr = ?
		]], usr)
	else
		file_attr(varpath('usr', usr, 'data'), {atime = time()})
	end
end

--update info (not really auth, but related) ---------------------------------

function auth.update(auth)

	local usr = allow(session_usr())
	local u   = userinfo(usr)
	allow(u.usr)

	local email = json_str_arg(auth.email)
	local phone = json_str_arg(auth.phone)
	local pass  = json_str_arg(auth.pass)
	local name  = json_str_arg(auth.name)

	if email then
		local eusr = email_usr(email)
		if eusr and eusr ~= usr then
			return nil,
				S('email_taken', 'Email already registered'),
				'email_taken'
		end
	end

	if phone then
		local pusr = phone_usr(phone)
		if pusr and pusr ~= usr then
			return nil,
				S('phone_taken', 'Phone already registered'),
				'phone_taken'
		end
	end

	pass = pass and bcrypt_hash(pass)

	if use_sql() then
		query([[
			update usr set
				#if auth.email then
					email = :email,
					emailvalid = if(email <=> :email, 0, emailvalid),
				#endif
				#if auth.phone then
					phone = :phone,
					phonevalid = if(phone <=> :phone, 0, phonevalid),
				#endif
				#if auth.pass then
					pass = :pass,
				#endif
				#if auth.name ~= nil then
					name = :name,
				#endif
				usr = usr
			where
				usr = :usr
			]], {
				auth = auth,
				email = email, phone = phone, pass = pass, name = name,
				usr = usr,
			})
	else
		local updates = {}
		if email then
			updates.email = email
			updates.emailvalid = (u.email == email) and u.emailvalid or false
		end
		if phone then
			updates.phone = phone
			updates.phonevalid = (u.phone == phone) and u.phonevalid or false
		end
		if pass then updates.pass = pass end
		if auth.name ~= nil then updates.name = name end
		fs_update_usr(usr, updates)
	end

	return usr
end

return auth_schema --so you can call schema:import'webb_auth'
