#!/bin/bash
cd "${0%test-all}" || exit 1
file="$1"

run_test() {
	../bin/luajit -e"package.path=package.path..';$PWD/?.lua'" ../lua/$1
}

cleanup() {
	rm -f test-stdout
}
trap cleanup EXIT INT TERM

if [[ $file ]]; then
	run_test $file
else
	fail=
	for file in $(cd ../lua; ls -1 *.lua); do
		touch test-stdout
		AUTO=1 run_test $file >test-stdout || fail="$fail $file"
		grep -q ok test-stdout && echo "OK $file" || echo "   $file"
	done
fi
if [[ $fail ]]; then
	echo "FAILED: $fail"
	exit 1
fi
exit 0
