#!/bin/sh
cd "${0%build-all}" || exit 1

for t in gcc cmake nasm; do
	command -v "$t" >/dev/null || { echo "$t missing"; exit 1; }
done

# minizip2 needs libcrypto for AES.
[[ -f /usr/include/openssl/ssl.h ]] || { echo "libssl-dev missing"; exit 1; }

# deps
xxhash/build
zlib-ng/build

# big
luajit/build
bearssl/build
libjpeg/build
mdbx/build
#mir/build

# small
bcrypt/build
blake3/build
cjson/build
cpu_supports/build
expat/build
genx/build
jsmin/build
ldecNumber/build
libspng/build
lpeglabel/build
lz4/build
md5/build
mdbx_schema/build
minizip2/build
pillow_simd/build
utf8proc/build
