#!/bin/sh
cd "${0%build}" || exit 1

build() {
	${X}gcc -c -O2 $C src/*.c -I. -I../lua-headers -ansi
	${X}gcc *.o -shared -o ../../bin/$P/clib/$D -L../../bin/$P $L
	rm -f      ../../bin/$P/$A
	${X}ar rcs ../../bin/$P/$A *.o
	rm *.o
}

if [ "$OSTYPE" = "msys" ]; then
	P=windows L="-s -static-libgcc -llua51" D=lpeglabel.dll A=lpeglabel.a build
elif [ "${OSTYPE#darwin}" != "$OSTYPE" ]; then
	echo NYI
else
	P=linux C=-fPIC L="-s -static-libgcc" D=lpeglabel.so A=liblpeglabel.a build
fi
