#!/bin/sh
cd "${0%build}" || exit 1

build() {
	${X}gcc -c -O2 $C -DZLIB_COMPAT -msse4.2 src/*.c -Isrc -I.
	${X}gcc *.o -shared -o ../../bin/$P/$D $L
	rm -f ../../bin/$P/$A
	rm -f      ../../bin/$P/$A
	${X}ar rcs ../../bin/$P/$A *.o
	rm *.o
}

if [ "$OSTYPE" = "msys" ]; then
	P=windows C=-DZLIB_DLL L="-s -static-libgcc" D=z.dll A=z.a build
elif [ "${OSTYPE#darwin}" != "$OSTYPE" ]; then
	P=osx C="-arch x86_64 -mmacosx-version-min=10.9" \
	L="-arch x86_64 -mmacosx-version-min=10.9 -install_name @rpath/libz.dylib" \
	D=libz.dylib A=libz.a build
else
	P=linux C="-fPIC" L="-s -static-libgcc" D=libz.so A=libz.a build
fi
