#!/bin/sh
cd "${0%build}" || exit 1

gcc -shared -o ../../bin/libutf8proc.so \
	-std=c99 -O2 -fPIC -Wsign-conversion -Wall -Wextra -pedantic -Isrc -DUTF8PROC_EXPORTS src/utf8proc.c \
	-s -static-libgcc
