name: test-all

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: debian:12
    steps:
      - name: Install git and dependencies
        run: apt-get update && apt-get install -y ca-certificates git libssl3
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure git safe.directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Run tests
        run: tests/test-all
